steps:

  - name: ":lambda: Deploy"
    command: ".buildkite/steps/deploy.bash"
    agents:
      queue: ${BUILDKITE_AGENT_META_DATA_QUEUE}
    plugins:
      docker-compose:
        run: node
    concurrency: 1
    concurrency_group: lambda-deploy
